JMose\CommandSchedulerBundle\Entity\ScheduledCommand:
    type: entity
    repositoryClass: JMose\CommandSchedulerBundle\Entity\Repository\ScheduledCommandRepository
    fields:
        id:
            type: integer
            length: null
            unique: false
            nullable: false
            id: true
            generator:
                strategy: IDENTITY
        name:
            type: string
            length: 100
            unique: false
            nullable: false
        command:
            type: string
            length: 100
            unique: false
            nullable: false
        arguments:
            type: text
            unique: false
            nullable: true
        cronExpression:
            type: string
            scale: 0
            length: 100
            unique: false
            nullable: true
            precision: 0
        lastExecution:
            type: datetime
            length: null
            unique: false
            nullable: false
        lastReturnCode:
            type: integer
            length: null
            unique: false
            nullable: true
        logFile:
            type: string
            length: 100
            unique: false
            nullable: true
        priority:
            type: integer
            length: null
            unique: false
            nullable: false
        executeImmediately:
            type: boolean
            length: null
            unique: false
            nullable: false
        disabled:
            type: boolean
            length: null
            unique: false
            nullable: false
        locked:
            type: boolean
            length: null
            unique: false
            nullable: false
